# 服务器端口配置
server:
  port: 8001

# mybatis配置
mybatis:
  mapper-locations: classpath*:/mapper/*Mapper.xml

# mysql配置
spring:
  datasource:
    url: jdbc:mysql://localhost/test?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver